#pragma once

#define PROJECT_EXTENSION ".shb"
#define PROJECT_NAME_SIZE 32
#define PROJECT_NAME_DEFAULT "New Project"

#define APPLICATION_VERSION "0.1"
#define APPLICATION_NAME "Shader Builder"
#define APPLICATION_NAME_AND_VERSION "Shader Builder 0.1"

#define WINDOW_MIN_WIDTH 400
#define WINDOW_MIN_HEIGHT 300

#define GUI_SELECTIONPANEL_MIN_SIZE 100
#define GUI_SELECTIONPANEL_DEFAULT_SIZE 150
#define GUI_INSPECTORPANEL_MIN_SIZE 150
#define GUI_INSPECTORPANEL_DEFAULT_SIZE 150
#define GUI_OUTPUTPANEL_MIN_SIZE 100
#define GUI_OUTPUTPANEL_DEFAULT_SIZE 150
#define GUI_CONTENTPANEL_MIN_SIZE 100
