#pragma once

#define APPLICATION_CONFIG_FILEPATH "./config.json"
#define APPLICATION_NAME "Shader Builder"
#define APPLICATION_NAME_AND_VERSION "Shader Builder v0.1"
#define APPLICATION_SESSION_FILEPATH "./session.json"
#define APPLICATION_VERSION "0.1"

#define GUI_CONTENTPANEL_MIN_SIZE 100
#define GUI_INSPECTORPANEL_DEFAULT_SIZE 150
#define GUI_INSPECTORPANEL_MIN_SIZE 150
#define GUI_OUTPUTPANEL_DEFAULT_SIZE 150
#define GUI_OUTPUTPANEL_MIN_SIZE 100
#define GUI_SELECTIONPANEL_DEFAULT_SIZE 150
#define GUI_SELECTIONPANEL_MIN_SIZE 100
#define GUI_SOURCEPANEL_MIN_SIZE 150
#define GUI_VARYINGPANEL_DEFAULT_SIZE 350
#define GUI_VARYINGPANEL_MIN_SIZE 150

#define PROJECT_DEFAULT_PATH "./"
#define PROJECT_EXTENSION ".sbp"
#define PROJECT_NAME_SIZE 32
#define PROJECT_NAME_DEFAULT "NewProject"

#define SHADER_DEFAULT_PATH "shaders/"
#define SHADER_EXTENSION ".sc"
#define SHADER_NAME_DEFAULT "new_shader"
#define SHADER_NAME_SIZE 32
#define SHADER_TYPE_COMPUTE "compute"
#define SHADER_TYPE_FRAGMENT "fragment"
#define SHADER_TYPE_VERTEX "vertex"
#define SHADER_TYPES {SHADER_TYPE_VERTEX,SHADER_TYPE_FRAGMENT,SHADER_TYPE_COMPUTE}
#define SHADER_VARYING_FILENAME "varying.def.sc"

#define TAB_SOURCE_SHADER 0
#define TAB_SOURCE_LIBRARY 1
#define TAB_SOURCE_OUTPUT 2

#define WINDOW_MIN_HEIGHT 300
#define WINDOW_MIN_WIDTH 400

